version: '3'
services:
  origin:
    image: python:3.11
    working_dir: /origin
    volumes:
      - ./origin:/origin
    command: python -m http.server 8001

  edge1:
    build: .
    volumes:
      - ./edge1_cache:/app/disk_cache
    command: python edge/edge_server.py --port 8081

  edge2:
    build: .
    volumes:
      - ./edge2_cache:/app/disk_cache
    command: python edge/edge_server.py --port 8081

  edge3:
    build: .
    volumes:
      - ./edge3_cache:/app/disk_cache
    command: python edge/edge_server.py --port 8081

  load_balancer:
    build: .
    command: python load_balancer.py
    ports:
      - "8080:8080"
    depends_on:
      - edge1
      - edge2
      - edge3
      - origin
